services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapps-dashboard
    environment:
      - APP_KEY=base64:***REMOVED***=
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://adminka.synapps.sk
      - DB_CONNECTION=pgsql
      - DB_HOST=synapps-pgsql
      - DB_PORT=5432
      - DB_DATABASE=synapps_dashboard
      - DB_USERNAME=dashboard_user
      - DB_PASSWORD=v9qcX5vp&r
      - QUEUE_CONNECTION=database
    labels:
      - "traefik.enable=true"
      # HTTPS router
      - "traefik.http.routers.synapps-dashboard.rule=Host(`adminka.synapps.sk`)"
      - "traefik.http.routers.synapps-dashboard.entrypoints=websecure"
      - "traefik.http.routers.synapps-dashboard.tls.certresolver=myresolver"
      - "traefik.http.services.synapps-dashboard.loadbalancer.server.port=8000"
      # HTTP redirect router
      - "traefik.http.routers.synapps-dashboard-http.rule=Host(`adminka.synapps.sk`)"
      - "traefik.http.routers.synapps-dashboard-http.entrypoints=web"
      - "traefik.http.routers.synapps-dashboard-http.middlewares=redirect-to-https"
      # Define the redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    networks:
      - web
      - database
    expose:
      - "8000"

networks:
  web:
    external: true
  database:
    external: true
