services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapps-dashboard
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://admin.synapps.sk
      - DB_CONNECTION=pgsql
      - DB_HOST=synapps-postgres
      - DB_PORT=5432
      - DB_DATABASE=synapps_dashboard
      - DB_USERNAME=dashboard_user
      - DB_PASSWORD="v9qcX5vp&r"
      - QUEUE_CONNECTION=database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapps-dashboard.rule=Host(`admin.synapps.sk`)"
      - "traefik.http.routers.synapps-dashboard.entrypoints=websecure"
      - "traefik.http.routers.synapps-dashboard.tls.certresolver=myresolver"
      - "traefik.http.services.synapps-dashboard.loadbalancer.server.port=9000"
    networks:
      - web
      - database
    expose:
      - "9000"

networks:
  web:
    external: true
  database:
    external: true
