services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synapps-dashboard
    environment:
      - APP_KEY=base64:***REMOVED***=
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://adminka.synapps.sk
      - DB_CONNECTION=pgsql
      - DB_HOST=synapps-pgsql
      - DB_PORT=5432
      - DB_DATABASE=synapps_dashboard
      - DB_USERNAME=dashboard_user
      - DB_PASSWORD=***REMOVED***
      - QUEUE_CONNECTION=database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminka.rule=Host(`adminka.synapps.sk`)"
      - "traefik.http.routers.adminka.entrypoints=web"
      - "traefik.http.services.adminka.loadbalancer.server.port=8000"
      - "traefik.docker.network=web"  # This tells Traefik to use the web network!
    networks:
      - web
      - database

networks:
  web:
    external: true
  database:
    external: true
