<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Per-user cache of the day's coach "pokes" — short motivational notification
 * texts generated by the coach LLM from the athlete's context (persona, today's
 * session state, check-in energy, streak). Shape:
 * { date, done, energy, items: [{slot, at, title, body}] }.
 * Regenerated when the date or context changes; one LLM call a day at most.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('stride_profiles', function (Blueprint $table) {
            $table->json('daily_pokes')->nullable()->after('preferences');
        });
    }

    public function down(): void
    {
        Schema::table('stride_profiles', function (Blueprint $table) {
            $table->dropColumn('daily_pokes');
        });
    }
};
