#!/usr/bin/env python3
"""
Stamp thumbnail_url into data/freestyle_tricklist.json for every trick whose
poster frame exists in tricklist_thumbs/ (generated by tricklist_thumbs.sh and
uploaded to s3://…/stride/exercises/thumbs/). Run after the S3 upload.
"""

from __future__ import annotations

import json
import pathlib

HERE = pathlib.Path(__file__).parent
DATA = HERE.parent / "data" / "freestyle_tricklist.json"
THUMBS = HERE / "tricklist_thumbs"

S3_THUMBS = "https://public-synapps-dashboard.nbg1.your-objectstorage.com/stride/exercises/thumbs"


def main() -> None:
    rows = json.loads(DATA.read_text())
    stamped = 0
    for row in rows:
        video_url = row.get("video_url")
        if not video_url:
            continue
        slug = video_url.rsplit("/", 1)[-1].removesuffix(".mp4")
        if (THUMBS / f"{slug}.jpg").exists():
            row["thumbnail_url"] = f"{S3_THUMBS}/{slug}.jpg"
            stamped += 1

    DATA.write_text(json.dumps(rows, indent=2, ensure_ascii=False) + "\n")
    print(f"Stamped thumbnail_url on {stamped}/{len(rows)} tricks -> {DATA}")


if __name__ == "__main__":
    main()
